### ISSUE TITLE
你好，插件怎么样安装呢？

### ISSUE THREAD

**Issue by minminaya** [compose-museum/compose-code-helper#13]
应用市场需要搜索什么关键字呢？
尝试使用 compose 和 compose-code-helper 但是搜出来的感觉不是一个插件
![image](https://user-images.githubusercontent.com/18503592/148885544-d6f9ae13-3bad-422e-afe0-66726b4e1053.png)

**Comment by Nthily** [comment]
你好，现在这个插件因为我们还没时间写耽搁下来了，很不好意思，之后如果发布到插件市场了会通知你的

**Comment by minminaya** [comment]
噢噢好咯，感谢

**Comment by weizhizhu** [comment]
现在发布到插件市场了吗 搜了下没有发现

**Comment by Nthily** [comment]
> 
没有，目前还没有时间写，发布的话会发 release 的
